### ISSUE TITLE
PBS or local machine

### ISSUE THREAD

**Issue by slambrechts** [Finn-Lab/MAG_Snakemake_wf#2]
Hi,

Great resource! I have two questions:

1) Can I use this workflow on a PBS cluster system instead of a SLURM or LSF one?
2) Or alternatively, can I use a single machine (local execution) with a lot of memory and threads?

And could you give an example on how the workflow should be run on these (with for example a machine or cluster with 36 processors and 738GB memory)?

**Comment by sskashaf** [comment]
Hi Sam,

1. Yes, you can. 2. For optimal resource usage, I would recommend against local execution.

I don't have experience with the PBS cluster system but I would imagine you can just change this line (--cluster "sbatch -n {cluster.nCPU} --mem {cluster.mem} -e {cluster.error} -o {cluster.output} -t {cluster.time}") to what it would be for a PBS cluster system (eg. change sbatch to qsub, etc).

Also, in this protocol, we use a cluster configuration file, which has now been deprecated. If you are interested, I would recommend using a cluster profile. Here is one for the PBS cluster:

https://github.com/Snakemake-Profiles/pbs-torque.

It will require adding the resources to the rules themselves as explained in detail here:

http://bluegenes.github.io/Using-Snakemake_Profiles/

-Sara

**Comment by choon-sim** [comment]
hi @slambrechts, 
I am wondering if you solved the issue? I am also using a PBS cluster, and couldn't get the pipeline to run.
