### ISSUE TITLE
Adapting the clusterconfig file for PBS

### ISSUE THREAD

**Issue by zckoo007** [Finn-Lab/MAG_Snakemake_wf#4]
Hi, I just make a test,but get an error, where is workflow set?

$ snakemake Snakefile 
MAG_Snakemake_wf-master/modules/sra_download.Snakefile:
'Workflow' object has no attribute 'cores'
  File "MAG_Snakemake_wf-master/Snakefile", line 75, in <module>
  File "MAG_Snakemake_wf-master/modules/sra_download.Snakefile", line 26, in <module>

**Comment by sskashaf** [comment]
Hello, 

As described [here](https://github.com/Finn-Lab/MAG_Snakemake_wf): the command that should be run for SLURM is: 

```
snakemake --use-singularity --restart-times 3 -k -j 50 --cluster-config clusterconfig.yaml --cluster "sbatch -n {cluster.nCPU} --mem {cluster.mem} -e {cluster.error} -o {cluster.output} -t {cluster.time}"
```

and for LSF:

```
snakemake --use-singularity --restart-times 3 -k --jobs 50 --cluster-config clusterconfig.yaml --cluster "bsub -n {cluster.nCPU} -M {cluster.mem} -e {cluster.error} -o {cluster.output}"

```
Please let me know if this does not resolve the issue.

-Sara

**Comment by zckoo007** [comment]
dear sskashaf 

we only have “qsub“ cluster. would you please set a qsub cmd ?

```
#PBS -N bin
#PBS -l nodes=1:ppn=5
#PBS -q default
#PBS -j oe
#PBS -l walltime=120:00:00
```

**Comment by sskashaf** [comment]
Hello,

Can you try editing the clusterconfig file for each rule (an example is shown below):

```
__default__:
  jobname: "{rule}"
  nodes: 1
  ppn: 1
  mem: "1000mb"
  time: "5:00"
  output: "logs/{rule}.%J.o"
  ```
  
  Then you can submit the job as such:
  ```
  snakemake --use-singularity --restart-times 3 -k -j 50 --cluster-config clusterconfig.yaml --cluster "qsub -l select={cluster.nodes}:ncpus{cluster.ppn}:mem={cluster.mem} -l walltime={cluster.time} -o {cluster.output}"
```

**Comment by choon-sim** [comment]
Hi @zckoo007,
did the solution work for you? I am wondering as I am also using a pbs cluster.
