### ISSUE TITLE
Python versioning issues

### ISSUE THREAD

**Issue by lauren-mak** [Finn-Lab/MAG_Snakemake_wf#5]
I've been trying to set up MAG_Snakemake_Wf on our compute cluster and run it on the test datasets as you've described. Singularity doesn't work properly for some reason, so I've been using conda to manage dependencies. Everything works great until the binning step, where I run into an issue. MetaWRAP, CONCOCT, and MyCC depend on Python 2, whereas the rest of the programs work fine with Python 3. I've gotten around this by adding a conda environment YAML to the binning Snakefile, but that's kind of hacky. Are there better ways of managing this?

**Comment by sskashaf** [comment]
Hi Lauren, 

metaWRAP is a bit tricky to install. Maybe you can try installing metaWRAP via conda (metawrap-mg=1.2.3). You can install CONCOCT separately (download from https://github.com/BinPro/CONCOCT/archive/1.1.0.tar.gz). Also don't forget to download the CheckM database (https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_2015_01_16.tar.gz) which I had downloaded inside the container. And make sure to run the checkm data setRoot command before using the tool as discussed here: https://github.com/bxlab/metaWRAP. Does this help?

Best wishes,
Sara

**Comment by sskashaf** [comment]
Did this answer your question?

**Comment by lauren-mak** [comment]
Sorry about the late response! Unfortunately, installing the conda versions of MetaWRAP did not work. Strangely enough, downloading directly from [Anaconda](https://anaconda.org/ursky/metawrap-mg/files) did. However, this still does not solve my version problem, since MetaWRAP depends on Python 2 instead of 3. Are there any workarounds for this?

**Comment by sskashaf** [comment]
You can create a snakemake conda environment yaml like what I have included below. Then you can run everything with snakemake --use-conda ... Also don't forget to add conda:"/path/to/yaml" to rule definition.

```
name: metawrap
channels:
  - ursky
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - metawrap-mg [insert version]
  - python=2.7
  ```

**Comment by lauren-mak** [comment]
I'll try that, thanks! To confirm, this will have to be run separate from the main MAG Snakemake Workflow pipeline, correct?

**Comment by sskashaf** [comment]
No, you will use the same pipeline except now the environments will be defined via conda rather than singularity (more info on using conda environments with snakemake is here (https://snakemake.readthedocs.io/en/v3.10.1/snakefiles/deployment.html)
